Contacts + Sessions + Account Info Dump
3bl3gamer/tg-history-dumper pull request #7
Opened 2021-06-29 09:28 UTC by patrizok

2021-07-04 20:42 UTC, 3bl3gamer requested changes
Hello! Thank you for the pull request!

But there are some problems.

## General

Account/contacts/auths should be configurable via `config.json`. Currently they will be saved on every run which may be undesirable: someone may have a lot of contacts but willing to update just one chat.

They must not update on `--list-chats`.

There should be an append option. Currently everything is appended: users, chats and (of course) messages. But account/contacts/auths will be completely overwritten. Maybe switch this via config? Like `{"contacts":"off"` / `{"contacts":"overwrite"` / `{"contacts":"append"`?

Since account/contacts/auths are saved as-is (exactly in format they come from TG), they should
a) have `"_"` field with type and
b) have `"_TL_LAYER"` field with API version (like messages: [README](https://github.com/3bl3gamer/tg-history-dumper#messages), [code example](https://github.com/3bl3gamer/tg-history-dumper/blob/master/saver.go#L334-L335)).

They should also have `"UpdatedAt"` field as users/chats do (at least in append mode).

P.S.: you are Russian, aren't you?

2021-07-04 20:42 UTC, 3bl3gamer commented on saver.go
> +func (s JSONFilesHistorySaver) openForCreate(fpath string) (*os.File, error) {
Weird name. Maybe `openAndTruncate`?

2021-07-04 20:42 UTC, 3bl3gamer commented on saver.go
> +	if encoder == nil {
It's always `nil`, so the check is unnecessary. It could be just `encoder := json.NewEncoder(file)`.

2021-07-04 20:42 UTC, 3bl3gamer commented on saver.go
> +	if encoder == nil {
Same as `SaveContacts`

2021-07-04 20:42 UTC, 3bl3gamer commented on saver.go
> +	if encoder == nil {
Same as `SaveContacts`

2021-07-04 20:42 UTC, 3bl3gamer commented on tg.go
> +	saver.SaveAccount(me)
No saves should occur here. `tgConnect` should just connect. However, it can return `TL_user` as the second value (before error).

2021-07-05 11:55 UTC, patrizok commented
Hi,
Thank you for your detailed suggestions.

• I update .gitignore file to prevent updating config and dump files.
• I resolve the problems that you point.
• I do not support updating session and contact right now. Because Telegram already return all data in one response. It can be disabled by config.json or command line parameters. UpdatedAt is not required also.
• Config.json supports enable and disable new features.
• Command line parameter enable disable works.
• Not update on --list-chats
• Document updated, but .zh document is not updated. You can update it later.

> Since account/contacts/auths are saved as-is (exactly in format they come from TG), they should
> a) have "_" field with type and
> b) have "_TL_LAYER" field with API version (like messages: README, code example).

• This is the only thing that I not implement. I don't know why users need the type and layer version.
Adding these information to dump files also increase code complexity, chats and users file also does not have this information.

I am not Russian by the way I'm from UK ;)

2021-07-05 19:59 UTC, 3bl3gamer requested changes
> .zh document is not updated

I dont't know Chinese either :) Just copy new parts (in English) to zh.md and maybe someone will translate them later.

> why users need the type and layer version
> chats and users file also does not have this information

That's because chats and users format is defined in [dumper's source](https://github.com/3bl3gamer/tg-history-dumper/blob/master/saver.go#L16-L23), have only limited amount of fields and most likely will not change.

[User](https://github.com/3bl3gamer/tgclient/blob/7cc3e61624657aae935e8d3c92ea8dd886a4da27/mtproto/tl_schema.go#L1991), [Contact](https://github.com/3bl3gamer/tgclient/blob/7cc3e61624657aae935e8d3c92ea8dd886a4da27/mtproto/tl_schema.go#L2701) and [Authorization](https://github.com/3bl3gamer/tgclient/blob/7cc3e61624657aae935e8d3c92ea8dd886a4da27/mtproto/tl_schema.go#L4071) (huge 32k-line pages, beware) on the other hand are defined by Telegram API and may change with a high probability in the next API version (especially User). Without `_TL_LAYER` some quirks with fields presence/absence checks may be required when processing saved jsons. There is also `TL_contact.Mutial` field which is either `TL_boolTrue` or `TL_boolFalse`, and without type annotation both will be just `{}` .

Type (`"_"`) here is mostly for consistency with other exported TG API structs (in messages).

> TL_contacts_contacts

There are just IDs with separate `TL_contacts_contacts.Users` array. It should also be saved via `SaveRelatedUsers` (in case a contact has empty message history, etc).

2021-07-06 07:57 UTC, patrizok commented
Hi,

As you mentioned changes applied.

2021-07-06 13:13 UTC, 3bl3gamer requested changes
Aaand what about this comment https://github.com/3bl3gamer/tg-history-dumper/pull/7#pullrequestreview-699377378 ?

2021-07-06 13:13 UTC, 3bl3gamer commented on README.md
> +# Telegram History Dumper
OMG o_O
thank you

2021-07-06 14:01 UTC, 3bl3gamer commented
> rename tg.session.temp tg.session: The process cannot access

Fixed this one. You can check it by updating `github.com/3bl3gamer/tgclient` dependency to `v0.126.1`

2021-07-07 09:34 UTC, patrizok commented on README.md
> +# Telegram History Dumper
:)

2021-07-07 09:43 UTC, patrizok commented
I update depencencies

With new version of **github.com/3bl3gamer/tgclient** file IO problem fixed but there is an another problem with Windows. 
I can not understand problem with errorcode.

> [ERROR] :
> unexpected response: mtproto.TL_bad_msg_notification{BadMsgID:6982098918416156760, BadMsgSeqno:7, ErrorCode:33}
> 
> main.tgConnect
>         /home/kali/Desktop/tg-history-dumper/tg.go:101
> main.dump
>         /home/kali/Desktop/tg-history-dumper/main.go:242
> main.main
>         /home/kali/Desktop/tg-history-dumper/main.go:333
> runtime.main
>         /usr/lib/go-1.15/src/runtime/proc.go:204
> runtime.goexit
>         /usr/lib/go-1.15/src/runtime/asm_amd64.s:1374
--------------

_Id dump comes with the TL_contacts_contacts.Users -> Contacts array_ seems **not required** because even if I do not start chat contact already comes in Users array. (contact has empty message history, etc) hypotheses not work here. Users and Contacts already mingling with each other adding SaveRelatedUsers file will be puzzle if not really required.

> There are just IDs with separate TL_contacts_contacts.Users array. It should also be saved via SaveRelatedUsers (in case a contact has empty message history, etc).

-------------------

 Comment #7 ( "_TL_LAYER" and "_" ) done right now.
I am not good at dependency management with go, so can you please check the mod and sum files.

2021-07-07 14:18 UTC, 3bl3gamer requested changes
> unexpected response: mtproto.TL_bad_msg_notification

That's a bug with `tgclient`. It happens sometimes when client gets interrupted during connection. And gets fixed after 2-4 re-connections.

> TL_contacts_contacts.Users/Contacts 

Not sure about this one. So there are two options:

First is to save `TL_contacts_contacts.Users`. The result will a) be easier to process and b) contain some extra fields which are missing in `history_my/users` (last status, bot/scam flag, etc.)

Another one is to save `TL_contacts_contacts.Contacts`. The result will a) have `Mutual` flag b) will be easily comparable with previous one in append mode.

What do you think? Do you prefer `TL_contacts_contacts.Users`?

2021-07-07 15:58 UTC, patrizok commented
1 - Actually there is no reason to reverse contacts, it doesn't matter, but I changed it to avoid misunderstanding.
2 - I run your code and I checked TL version downgraded to 126 in dump files.
3 - Let's leave it as it is for easy processing (**TL_contacts_contacts.Users**). If someone need **b** options, then it can be changed.

2021-07-07 17:01 UTC, 3bl3gamer commented
Cool! Thank you again, will merge it now.

I will also merge some changes soon which will fix log colors on Windows. If it won't work, fell free to open another issue!

2021-07-07 17:04 UTC, merged